haproxytech/helm-charts

kubernetes-ingress/README.md

When using helm cli  with `--set` parameters, one also need to escape
commas ',' in the value string, such as:
helm upgrade syslog haproxytech/kubernetes-ingress \
--set controller.config."syslog-server"="address:127.0.0.1\, facility:local0\, format:raw\, level:notice"
otherwise such error is returned:
Error: failed parsing --set data: key " format:raw, level:notice" has no value

MINOR: README: add warning about comma in value string

---

kubernetes-ingress/Chart.yaml
kubernetes-ingress/templates/_helpers.tpl
kubernetes-ingress/templates/controller-daemonset.yaml
kubernetes-ingress/templates/controller-deployment.yaml
kubernetes-ingress/values.yaml

MINOR: add publishService
When enabled the <namespace>/<service-name> matching the controller's
service will be used by default, unless this is overriden by
pathOverride.

New release 0.5.0 including publishService value

---

kubernetes-ingress/templates/controller-daemonset.yaml

Add a conditional to remove hostNetwork when hostPorts are disabled to prevent automatic creation of hostPort records regardless of their presence in the template.
Fixes #3 
Signed-off-by: Daniel Sullivan <dsullivan@charm.co.jp>

Fix to enable disabling hostPorts

---

kubernetes-ingress/templates/controller-daemonset.yaml
kubernetes-ingress/templates/controller-deployment.yaml
kubernetes-ingress/templates/controller-service.yaml
kubernetes-ingress/values.yaml

Make the Kubernetes service of the controller expose additional ports
via tcpPorts param.
This is particularly useful when the HAProxy ingress controller is used
to handle TCP services.

MINOR: Expose ports for additional TCP services

---

kubernetes-ingress/Chart.yaml
kubernetes-ingress/templates/controller-configmap.yaml
kubernetes-ingress/templates/controller-daemonset.yaml
kubernetes-ingress/templates/controller-defaultcertsecret.yaml
kubernetes-ingress/templates/controller-deployment.yaml
kubernetes-ingress/templates/controller-pullsecret.yaml
kubernetes-ingress/templates/controller-service.yaml
kubernetes-ingress/templates/controller-serviceaccount.yaml
kubernetes-ingress/templates/default-backend-deployment.yaml
kubernetes-ingress/templates/default-backend-service.yaml

This is fully backward compatible and make it just more compatible with workflows using `helm template`.
Adding release.Namespace in meta fixes issues when rendering template with 'helm template --namespace'. Without it, the rendered templates do not have the namespace defined which is problematic when using a gitops approach. This is also a requirement for a tool like Spinnaker.
Signed-off-by: lcavajani <lcavajani@suse.com>

Add release.Namespace in meta

---

kubernetes-ingress/Chart.yaml
kubernetes-ingress/templates/controller-daemonset.yaml
kubernetes-ingress/templates/controller-deployment.yaml
kubernetes-ingress/templates/controller-service.yaml
kubernetes-ingress/values.yaml

In some setups, external components like a TCP loadbalancer need to know the nodePorts where the controller is exposed.
This commit adds the option to define nodePorts for the default services http, https and stat.
It also adds this option for tcpPorts but **this introduces a breaking change** as a tcpPort must now be a map with name, port, targetPort and optionnaly nodePort.
Signed-off-by: lcavajani <lcavajani@suse.com>

Allow the use of specific nodePorts

---

kubernetes-ingress/Chart.yaml
kubernetes-ingress/templates/_helpers.tpl
kubernetes-ingress/templates/clusterrolebinding.yaml
kubernetes-ingress/templates/controller-podsecuritypolicy.yaml
kubernetes-ingress/templates/controller-role.yaml
kubernetes-ingress/templates/controller-rolebinding.yaml
kubernetes-ingress/templates/default-backend-deployment.yaml
kubernetes-ingress/templates/default-backend-podsecuritypolicy.yaml
kubernetes-ingress/templates/default-backend-role.yaml
kubernetes-ingress/templates/default-backend-rolebinding.yaml
kubernetes-ingress/templates/default-backend-serviceaccount.yaml
kubernetes-ingress/values.yaml

I've tested this on Kubernetes `1.17.4` with upgrading from the previous version (no PSP, no SA for default-backend). When upgrading, with the default values:
*  the `default-backend` pods will be recreated since it is set to use a new `ServiceAccount`. Setting `defaultBackend.defaultBackend.create: false` would disable this by default but I think it's good practice to use a specific `ServiceAccount`.
* PSP are disabled, enabling them is not disruptive
After Enabling PSP, it's required to delete the pods, the pods are correctly using the PSPs
```
$ kubectl -n cluster-addons get po haproxy-kubernetes-ingress-9cv7x -ojson | jq '.metadata.annotations'
{
"container.apparmor.security.beta.kubernetes.io/kubernetes-ingress-default-backend": "runtime/default",
"kubernetes.io/psp": …
```

Add PSP support and SA for default backend

---

kubernetes-ingress/Chart.yaml
kubernetes-ingress/templates/controller-service.yaml
kubernetes-ingress/values.yaml

- leave the default behaviour to have http, https and stat enabled
- add the option to disable http, https and stat
- bump chart version

add enablePorts for controller.service to allow better control of which ports are enabled

---

kubernetes-ingress/templates/controller-deployment.yaml
kubernetes-ingress/templates/default-backend-deployment.yaml
kubernetes-ingress/values.yaml

I am opening a new PR, which the changes suggested in #20, because I don't have permissions to re-open #20.
@dkorunic this one keeps the default value for `replicas` but also makes it optional.
Could you have another look?
Thanks!

Make replicaCount definition optional

---

kubernetes-ingress/templates/controller-deployment.yaml
kubernetes-ingress/templates/default-backend-deployment.yaml

After #21 a value of `0` for `controller.replicaCount` and `defaultBackend.replicaCount` is treated as an empty/null value.
This PR makes `0` treated as a proper value. (Setting `replicaCount` to `0` makes sense in certain cases especially for the default backend)

Make replicaCount accept 0 as a valid value

---

kubernetes-ingress/templates/controller-service.yaml
kubernetes-ingress/values.yaml

Support changing the service's sessionAffinity setting to something other than the default ("None"), .e.g: to "ClientIP"

Support service's sessionAffinity definition

---

kubernetes-ingress/templates/controller-daemonset.yaml
kubernetes-ingress/templates/controller-podsecuritypolicy.yaml
kubernetes-ingress/values.yaml

Hello.
This PR adds possibilty to use `hostPort` without having  `hostNetwork: true` in pod. 
**Why this PR?** 
I'm using netwokpolicies on my kubernetes cluster. Network policies don't apply to `hostNetwork: true` pods.
Ingress controller with  `hostNetwork: true` enabled can't access `kind: Ingress` objects of the namespaces with kubernetes `kind: NetworkPolicy` objects enabled (allow rules dont't work for `hostNetwork: true` pods)
Regards

hostPort without hostNetwork

---

kubernetes-ingress/templates/controller-daemonset.yaml
kubernetes-ingress/templates/controller-deployment.yaml
kubernetes-ingress/templates/default-backend-deployment.yaml
kubernetes-ingress/values.yaml

Add `.Values.controller.extraEnvs` and `.Values.defaultBackend.extraEnvs` to set additonal environment variables like `TZ` to set time zone [link](https://github.com/haproxytech/kubernetes-ingress/blob/1d44fbb5a5d4c2df566c8aada4f2c25c459e9125/deploy/haproxy-ingress-daemonset.yaml#L162-L164). 
This merge request is better than from my last pull request [#32](https://github.com/haproxytech/helm-charts/pull/32) that was specifically try to add `TZ` environment variable.

MINOR: add extraEnvs to set additional envs

---

kubernetes-ingress/templates/controller-defaultcertsecret.yaml

Creates default TLS secret conditionally via existing `controller.defaultTLSSecret.enabled` flag. Currently this secret is always created resulting in the below changes being reported on every helm diff as the cert is regenerated:
```
data:
-   tls.crt: '-------- # (1127 bytes)'
-   tls.key: '-------- # (1671 bytes)'
+   tls.crt: '++++++++ # (1172 bytes)'
+   tls.key: '++++++++ # (1679 bytes)'
type: kubernetes.io/tls
```

Only create default tls secret when enabled

---

kubernetes-ingress/README.md
kubernetes-ingress/templates/_helpers.tpl
kubernetes-ingress/templates/controller-servicemonitor.yaml
kubernetes-ingress/values.yaml

Since HAProxy is already serving Prometheus metrics on 1024 port, would be great having also the `ServiceMonitor` template in order to automate scraping using the [Prometheus Operator](https://github.com/prometheus-operator/prometheus-operator) stack.
Default value is set to `false` in order to don't introduce breaking change due to non installed CRDs.
> Actually, scraping can be easily achieved using basic Prometheus installation and its Kubernetes service discovery capabilities thanks to the annotation `prometheus.io/scrape` but this is not powerful since it allows just defining the toggling, port, and path.

Adding support for Prometheus ServiceMonitor

---

kubernetes-ingress/templates/controller-daemonset.yaml
kubernetes-ingress/templates/controller-deployment.yaml
kubernetes-ingress/templates/default-backend-deployment.yaml
kubernetes-ingress/templates/default-backend-hpa.yaml
kubernetes-ingress/templates/default-backend-podsecuritypolicy.yaml
kubernetes-ingress/templates/default-backend-role.yaml
kubernetes-ingress/templates/default-backend-rolebinding.yaml
kubernetes-ingress/templates/default-backend-service.yaml
kubernetes-ingress/templates/default-backend-serviceaccount.yaml
kubernetes-ingress/values.yaml

This PR adds support for disabling default backend resources via `defaultBackend.enabled` flag.
When this flag is set to `false`, default backend won't be deployed and as a result HAProxy will use `503` error code in response to unknown vhosts, which itself may be required in some web hosting scenarios (like preventing search engines from un-listing pages).

FEATURE/MINOR: allow disabling default backend

---

haproxy/README.md
haproxy/templates/daemonset.yaml
haproxy/templates/deployment.yaml
haproxy/values.yaml
kubernetes-ingress/README.md
kubernetes-ingress/templates/controller-daemonset.yaml
kubernetes-ingress/templates/controller-deployment.yaml
kubernetes-ingress/values.yaml

We recently have a requirement to use a sidecar with haproxy but noticed there is no way to use an existing imagePullSecret which we already have within the same namespace as haproxy - this is a simple workaround for that situation.

allow for haproxy (sidecar?) to use an existing imagePullSecret

---

haproxy/templates/poddisruptionbudget.yaml
haproxy/values.yaml
kubernetes-ingress/templates/controller-poddisruptionbudget.yaml
kubernetes-ingress/values.yaml

Adding support of `PodDisruptionBudget` for bot haproxy and kubernetes-ingress helm charts to reduce downtime in production

Feature: pod disruption budget

---

haproxy/templates/podsecuritypolicy.yaml
haproxy/values.yaml

PodSecurityPolicy is a cluster-level resource. It is not needed in every deploy, so there should be an option to disable it.
Signed-off-by: Andrey Regentov <a.regentov@ftc.ru>

ability to disable PodSecurityPolicy

---

kubernetes-ingress/Chart.yaml
kubernetes-ingress/templates/controller-deployment.yaml
kubernetes-ingress/templates/default-backend-deployment.yaml
kubernetes-ingress/values.yaml

Hi,
this PR`s changes allow setting up topologySpreadConstraints for defaultBackend and/or controller pods.
This is also requested as enhancement here https://github.com/haproxytech/helm-charts/issues/60

Allow setting pod topologySpreadConstraints

---

kubernetes-ingress/templates/controller-daemonset.yaml
kubernetes-ingress/templates/controller-deployment.yaml
kubernetes-ingress/values.yaml

Allows the customization of the namespace for the default TLS secret instead of hard coding the namespace to the release namespace.
The default value in Values.yaml is set to the release namespace, as this is the most likely location for the secret. 
For these two files, note the changes on line 34.
Output for `helm template --debug .`:
[default-values-controller-deployment.txt](https://github.com/haproxytech/helm-charts/files/6351256/default-values-controller-deployment.txt)
Output for `helm template --debug . --set controller.defaultTLSSecret.secretNamespace=test-ns`:
[custom-namespace-controller-deployment.txt](https://github.com/haproxytech/helm-charts/files/6351255/custom-namespace-controller-deployment.txt)
Related: /haproxytech/kubernetes-ingress/issues/300

Added customizing default TLS secret namespace

---

kubernetes-ingress/templates/controller-hpa.yaml
kubernetes-ingress/templates/default-backend-hpa.yaml
kubernetes-ingress/values.yaml

It would be useful if the HPA created by the kubernetes-ingress Helm chart, could be configured to scale the number of HAProxy pods based on custom metrics other than CPU and memory utilization.
For example, auto-scale based on the number of backend connections or number of requests/second.
This is something that we have been doing for some time now by using a custom HPA definition outside of the Helm chart and would love to see it supported by the official chart.
It requires the use of something like https://github.com/kubernetes-sigs/prometheus-adapter
References:
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-custom-metrics
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#autoscaling-on-multiple-metrics-and-cu …

Support auto-scaling based on custom metrics

---

kubernetes-ingress/templates/controller-daemonset.yaml
kubernetes-ingress/templates/controller-deployment.yaml
kubernetes-ingress/templates/default-backend-deployment.yaml

Currently, `kubernetes-ingress.controller.extraEnvs` only accepts key-value transparent values.
However Kubernetes supports [using Secrets for environment variables](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables).
This PR allows chart users to define such environment values for the controller deployment, e.g.:
```yaml
kubernetes-ingress:
controller:
extraEnvs:
- name: TEST_STR
value: foo
- name: TEST_MAP
valueFrom:
secretKeyRef:
name: github
key: clientSecret
```
As you can see this change is backwards compatible with current behavior.
I left a comment in the implementation - not sure which approach you guys will prefer @Mo3m3n @dkorunic but please LMK!

Allow valueFrom usage with controller.extraEnvs

---

haproxy/README.md
haproxy/templates/configmap.yaml
haproxy/templates/deployment.yaml

- Always inject default pod annotation (that includes the hash of configmap)
- allow templates in configmap
- allow extraVolumes and VolumeMounts
I can split this up into 3 PRs if needed.
The rationale behind templating is that in our case, most of our hostnames are dynamic, so for our haproxy.cfg we'd need to do things like `server {{ .Release.Name }}-backend` which wasn't possible before.
We could get around this by manually creating our own `configmap` and using `config: null` in the values, however you lose out on some nice features like the `checksum/environment` annotation (which I changed to be included by default) as well as any future changes to the base configmap template.
The last extraVolumes and extraVolumeMounts fixes https://github.com/haproxytech/helm-charts/issues/75

New Helm chart features

---

kubernetes-ingress/Chart.yaml
kubernetes-ingress/templates/controller-daemonset.yaml
kubernetes-ingress/templates/controller-deployment.yaml

BUG/MINOR: kubernetes-ingress: Fixes typo in template evaluation of .Values.controller.defaultTLSSecret.secretNamespace

---

kubernetes-ingress/templates/default-backend-service.yaml
kubernetes-ingress/values.yaml

I'm not really a fan of running a dedicated default backend. Therefore I scaled it to "0" and just set an annotation on the default backend service object. This can certainly be useful for other cases, too.
The idea is not new: https://github.com/haproxytech/kubernetes-ingress/issues/71

Expose configuration for annotations of the default backend service

---

haproxy/templates/service.yaml
haproxy/values.yaml

This pull request adds the ability to control the `externalTrafficPolicy` option on the Service object.
This is necessary to be able to get real source IPs in most Kubernetes environments.

Add externalTrafficPolicy option to haproxy service

---

kubernetes-ingress/templates/controller-ingressclass.yaml
kubernetes-ingress/values.yaml

spec.controller field of IngressClass resource can now be configured by
appending the value of `--ingress.class` controller's argument.
This is useful when using multiple HAProy Ingress Controller instances
at the same time.
The spec.controller fix is available from 1.7.2
This patch introduces the following breaking changes:
1. Updating controller.ingressClass value makes Helm update
spec.controller field of the ingressClass resource. Note that this
field is immutable so helm upgrades with modified
controller.ingressClass value are going to fail.
2. controller.ingressClassResoruce.enabled was replaced by
controller.ingressClassResoruce.name

FEATURE/MEDIUM: Configure spec.controller field of IngressClass

---

kubernetes-ingress/templates/controller-daemonset.yaml
kubernetes-ingress/templates/controller-deployment.yaml

To accomodate a new feature in enterprise ingress controller a new environment variable POD_IP must be present.
This Ingress Controller feature concerns peers management.

MINOR: add POD_IP environment variable

---

kubernetes-ingress/templates/controller-daemonset.yaml
kubernetes-ingress/templates/controller-deployment.yaml

DaemonSet strategy was missing the required ENV and volumes.
Additionally, the `toYaml` for the `volumes` and `volumeMounts`, when combined with the additional AWS volumes required for the MarketPlace integration, was creating YAML errors, templating something like this:
```yaml
volumeMounts:
- name: aws-product-license
readOnly: true
mountPath: /var/run/secrets/product-license
- []
volumes:
- name: aws-product-license
secret:
secretName: foo
optional: true
- []
```
It has been fixed with the check `if gt (len .Values.controller.extraVolumes) 0` and `if gt (len .Values.controller.extraVolumeMounts) 0` to avoid printing an empty array. In case of no additional volumes, the specification keys `volumes` and `volumeMounts` are ignored and not rendered.

AWS MarketPlace bug fixes

---

kubernetes-ingress/Chart.yaml
kubernetes-ingress/templates/controller-configmap.yaml
kubernetes-ingress/values.yaml

Added a field `.controller.configAnnotations` to kubernetes-ingress helm chart to allow annotation customization on configmap.
Resolve issue https://github.com/haproxytech/kubernetes-ingress/issues/399
Signed-off-by: Ethern Su <ehaprime@gmail.com>

added config annotation field in kubernetes ingress chart;

---

haproxy/templates/configmap.yaml
haproxy/templates/daemonset.yaml
haproxy/templates/deployment.yaml
haproxy/values.yaml

Add new features HAProxy helm-charts:
- Automatically Roll Deployments(Helm) - enable/disable
- Share Process Namespace between Containers in a Pod
- Pods: How Pods manage multiple containers - sidecarContainers
- Change defaults command line arguments
- Controller Container liveness/readiness probe configuration
- Basic features : Maps - includes
- Topology spread constraints (only used in kind: Deployment)

add new features helm-charts

---

kubernetes-ingress/templates/controller-defaultcertsecret.yaml

To use a default TLS secret the `controller.defaultTLSSecret.secret` needs to be empty, yet the secret-generating template requires it to be non-empty.
This fix negates the condition on the key to restore desired functionality.
Original functionality:
Setting `controller.defaultTLSSecret.secret` to `null` (default) would not generate a default secret and yet pass its name to the Deployment, generating "secret missing" errors.

fix: Default TLS secret cannot be generated

---

kubernetes-ingress/templates/controller-daemonset.yaml
kubernetes-ingress/templates/controller-deployment.yaml
kubernetes-ingress/values.yaml

Add configurable minReadySeconds value

---

haproxy/ci/daemonset-probes-values.yaml
haproxy/ci/deployment-probes-values.yaml
haproxy/templates/daemonset.yaml
haproxy/templates/deployment.yaml
haproxy/values.yaml
kubernetes-ingress/templates/controller-daemonset.yaml
kubernetes-ingress/templates/controller-deployment.yaml
kubernetes-ingress/values.yaml

Hi team, these helm charts are very good.
However, in my case, I needed to set up the exec command in readinessProbe. 
Therefore, I have made some changes in this PR to freely declare the values of several probes.

feat: allow to set several probe more freely.

---

haproxy/ci/daemonset-probes-values.yaml
haproxy/ci/deployment-probes-values.yaml

Hi, team.
I fixed CI error due to [this PR](https://github.com/haproxytech/helm-charts/pull/128).
CI error is bellow:
```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(DaemonSet.spec.template.spec.containers[0].startupProbe): unknown field "enabled" in io.k8s.api.core.v1.Probe
```

fix(haproxy): ci error for instaliing haproxy chart.

---

haproxy/templates/service.yaml
haproxy/values.yaml

Allows defining `externalIPs` for the service. 
My use case is to get external-dns automation to work in behind NAT.
ref: https://kubernetes.io/docs/concepts/services-networking/service/#external-ips

haproxy: Allow defining externalIPs

---

haproxy/templates/hpa.yaml
haproxy/values.yaml

Hi team.
Since i want to configure [RPS metrics](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#autoscaling-on-multiple-metrics-and-custom-metrics) in HPA, we can configure additional metrics as additionalMetrics in this PR.

feat(haproxy): additional metrics for HPA.

---

haproxy/templates/NOTES.txt
haproxy/templates/_helpers.tpl
haproxy/templates/daemonset.yaml
haproxy/templates/deployment.yaml
haproxy/templates/hpa.yaml
haproxy/templates/ingress.yaml
haproxy/templates/keda.yaml
haproxy/templates/poddisruptionbudget.yaml
haproxy/templates/podsecuritypolicy.yaml
haproxy/templates/pullsecret.yaml
haproxy/templates/role.yaml
haproxy/templates/rolebinding.yaml
haproxy/templates/service.yaml
haproxy/templates/serviceaccount.yaml
haproxy/templates/servicemonitor.yaml
haproxy/values.yaml

This PR adds a way to override namespace for Haproxy helm chart if it is being used as dependency in another helm (umbrella) chart.

add namespaceOverride template to manifests

---

haproxy/templates/configmap.yaml

During testing of namespaceOverride I've noticed that everything is deployed as expected except configMaps, they are still deployed in the `.Release.namespace`

 namespaceOverride not used for configMaps

---

kubernetes-ingress/crds/core.haproxy.org_backends.yaml
kubernetes-ingress/crds/core.haproxy.org_defaults.yaml
kubernetes-ingress/crds/core.haproxy.org_globals.yaml

Listing on AWS MarketPlace requires CRDs manifests to be non-leaded by dashes (`---`).
Tested on a `kind` installation.
```
$: kind create cluster --name haproxy
Creating cluster "haproxy" ...
✓ Ensuring node image (kindest/node:v1.25.3) 🖼
✓ Preparing nodes 📦  
✓ Writing configuration 📜 
✓ Starting control-plane 🕹️ 
✓ Installing CNI 🔌 
✓ Installing StorageClass 💾
Set kubectl context to "kind-haproxy"
You can now use your cluster with:
kubectl cluster-info --context kind-haproxy
Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂
```
```
$: git log --name-status HEAD^..HEAD
commit 5cb74fb678446bb3b05723cb59eb6dea572170fc (HEAD -> crds, origin/crds)
Author: Dario Tranchitella <dario@tranchitella.eu>
Date:   Mon Nov 21 18:16:35 2022 +0100
REORG/MINOR: …
```

REORG/MINOR: removing leading dashes from CRDs manifests

---

kubernetes-ingress/templates/_helpers.tpl
kubernetes-ingress/templates/controller-service-metrics.yaml

This is an enhancement for an edge case.
Suppose the Kubernetes Ingress Controller is deployed using the Service type of LoadBalancer. In that case, the `stats` port will be public too, letting any potential attacker gather information about the metrics, and the internal endpoints, and reverse engineering the name of the service.
This can be prevented by installing the Ingress Controllers with the value `controller.service.enablePorts.stat=false` that will remove the `stats` port from the Service definition exposed using the type LoadBalancer.
However, this will break the Prometheus Operator integration through the `ServiceMonitor` resources, since the `EndpointSlice` objects will not contain anymore any available endpoint pointing to the stats port.
The proposed solution is to create a …

Exposing internal Service for metrics when using LoadBalancer and no stats

---

haproxy/Chart.yaml
haproxy/templates/service.yaml
haproxy/values.yaml

We want to scrape metrics of haproxy. We are using [haproxy exporter](https://github.com/prometheus/haproxy_exporter) as a side container to haproxy. However, now there is no possibility to add port of a side container to Service. This is needed for ServiceMonitor. 
This PR adds additionalPorts spec to pass ports of a side containers.

fix(haproxy): add additionalPorts to service

---

haproxy/templates/hpa.yaml

If you enabled the HPA and deploy with ArgoCD, the helm chart will always be detected as "OutOfSync" since k8ts will sort the resources list in the hpa cdr.
Have a look here for more info: https://github.com/argoproj/argo-cd/issues/1079

Reordering resources list in hpa

---

haproxy/templates/daemonset.yaml

This change exposes only those ports that are explicitly defined in daemonset.hostPorts. The remaining ports, which are defined only in containerPorts, will only be accessible from within the K8S cluster. This will allow to use one haproxy instance more universally.

haproxy: only defined hostPorts for DaemonSet

---

kubernetes-ingress/templates/clusterrole.yaml
kubernetes-ingress/values.yaml

Add the needed permissions to use the `techdump` tool.
New permissions are added only if `.Values.controller.techdump.enabled=true`, in order to not add them by default, only when needed.

MINOR: add permissions needed for techdump tool

---

kubernetes-ingress/templates/controller-deployment.yaml
kubernetes-ingress/values.yaml

Added ability to control `automountServiceAccountToken` value, which is defaulted to true.

MINOR: add 'automountServiceAccountToken` property

---

haproxy/templates/service.yaml
haproxy/values.yaml

Added the ability to set the internalTrafficPolicy attribute on the Service, which defaults to `Cluster`.
In combination with deploying HAProxy as a DaemonSet, setting internalTrafficPolicy to `Local` allows each Pod to only use the HAProxy instance on its local Node.

FEATURE/MINOR: haproxy: add 'internalTrafficPolicy' property for service

---

kubernetes-ingress/templates/controller-daemonset.yaml
kubernetes-ingress/values.yaml

when using hostPorts, it would be useful to also be able to set hostIP so two instances of ingress can run on two addresses

allow setting hostIP for daemonset

---

haproxy/templates/deployment.yaml

This modification enhances the flexibility of podAnnotations. It provides the option to utilize evaluation functions for an locale configmap, for example.
In my scenario, I'm using this chart as a dependency, and I have a local configmap. Therefore, I want the pods to rollout when the locale configmap is modified.
```yaml
...
podAnnotations:
checksum/local-environment: {{ include (print $.Template.BasePath "/my-local-configmap.yaml") . | sha256sum }}
...
```
This modification doesn't alter the current functionality.

feat: update podAnnotations rendering for better flexibility.

---

kubernetes-ingress/templates/controller-service-metrics.yaml
kubernetes-ingress/values.yaml

Adds `controller.service.metrics.labels` and
`controller.service.metrics.annotations` so that the metrics service can have its metadata templated using metadata not shared by the main service.

FEATURE/MINOR: kubernetes-ingress: Add metrics service-specific metadata

---

kubernetes-ingress/templates/controller-service-metrics.yaml
kubernetes-ingress/values.yaml

Adds `controller.service.metrics.type` so that the metrics service's type can be parametrized. The value defaults to `ClusterIP` for backwards compatibility with previous versions of the Helm chart.
We need the ability to do this because of a [bug in `external-dns`](https://github.com/kubernetes-sigs/external-dns/issues/187) but we unfortunately are not immediately able to upgrade `external-dns` to fix this bug.

FEATURE/MINOR: kubernetes-ingress: Parametrize metrics service type

---

kubernetes-ingress/values.yaml

Related to https://github.com/haproxytech/kubernetes-ingress/issues/633
Warn people that if they use the `logging` block, it will be completely ignored if they also use config.cr-global

DOC - logging block is replaced when cr-global is used.

---

haproxy/templates/NOTES.txt
haproxy/templates/daemonset.yaml
haproxy/templates/deployment.yaml
haproxy/values.yaml
kubernetes-ingress/templates/NOTES.txt
kubernetes-ingress/templates/controller-crdjob.yaml
kubernetes-ingress/templates/controller-daemonset.yaml
kubernetes-ingress/templates/controller-deployment.yaml
kubernetes-ingress/values.yaml

Follow on from https://github.com/haproxytech/helm-charts/pull/243.
Instead of passing a templated string value `tag: "{{ .Chart.AppVersion }}"` and relying on `tpl` inside the templates that consume it, it is safer, less complicated, and more standardized to:
1. Default to a falsey value i.e. `tag: ""`; and
2. place the "or default to the `.Chart.AppVersion`" logic inside the templates that consume that value.
For example, grafana's charts use this same pattern (I lifted it from there):
* https://github.com/grafana/helm-charts/blob/c8b0156b04dcf975ff1dbbbee570ee84503eb659/charts/grafana/values.yaml#L102-L103
* https://github.com/grafana/helm-charts/blob/c8b0156b04dcf975ff1dbbbee570ee84503eb659/charts/grafana/templates/_pod.tpl#L856
Since `tpl` expects a string, passing an unqouted, …

BUG: kubernetes-ingress: Replace tpl with default

---

kubernetes-ingress/templates/NOTES.txt
kubernetes-ingress/templates/controller-daemonset.yaml
kubernetes-ingress/templates/controller-deployment.yaml
kubernetes-ingress/templates/controller-proxy-deployment.yaml
kubernetes-ingress/templates/controller-service.yaml

This modification introduces two changes in templates:
- remove suffix `-tcp` on template controller.service.tcpPorts's name. Users add this suffix themselves if it's relevant to them.
- limit length to 15 characters max according to RFC6335.
Avoid errors like: 
````
Error: UPGRADE FAILED: cannot patch "release-name" with kind Deployment: Deployment.apps "release-name" is invalid: [spec.template.spec.containers[0].ports[6].name: Invalid value: "name-too-long-tcp": must be no more than 15 characters
````

fix(kubernetes-ingress): limit template spec name to 15 characters

---

kubernetes-ingress/templates/namespace.yaml

This pull request introduces an annotation "helm.sh/hook": "pre-install" to the namespace creation manifest in the haproxy-ingress chart. This change ensures that the namespace is created before any resources, including dependencies, are installed. This is particularly useful for users who want to manage namespaces and their associated resources using Helm, especially when they require specific annotations to be set on the namespace before deploying other resources.
Changes:
Added a namespace.yaml file in the templates directory with the necessary annotation.
Updated documentation to reflect the new annotation and its purpose.
Testing:
The change has been tested locally with the following setup:
Created a chart parent that includes haproxy-ingress as a dependency.
Confirmed that the …

Add pre-install hook annotation for namespace creation

---

kubernetes-ingress/templates/controller-keda.yaml
kubernetes-ingress/values.yaml

For one of my use cases, I need to be able to specify the name of the HPA object that KEDA's scaledObject will control.
The chart correctly allows one to specify behaviour of the HPA object but not the name of it.
Therefore I:
- Gave the ability to correctly specify `horizontalPodAutoscalerConfig` as the KEDA scaledObject itself has
- Gave the ability to specify the name of the object under this field
- Moved the behaviour block under the `horizontalPodAutoscalerConfig` block, as the original structure of the KEDA object is like this.
Using this configuration in conjunction with specifying the relevant annotations for the KEDA object will correctly have KEDA adopt the HPA object.

FEATURE/MINOR: Add ability to specify HPA name in KEDA scaledObject

---

kubernetes-ingress/templates/controller-daemonset.yaml
kubernetes-ingress/templates/controller-deployment.yaml
kubernetes-ingress/values.yaml

Analogous to https://github.com/haproxytech/helm-charts/pull/252, but for `kubernetes-ingress` chart.

feat(kubernetes-ingress): Add Values.controller.extraEnvFrom to deployment and daemonset

---

kubernetes-ingress/templates/controller-crdjob.yaml
kubernetes-ingress/values.yaml

**Adding possibility to set annotations on the crdjob**
**_Motivation:_**
On our clusters we run a service mesh (linkerd)
The linkerd sidecar container (linkerd-proxy) gets auto-injected into any pod in the namespace we deploy haproxy into.
For k8s jobs there is a known limitation (see: https://github.com/linkerd/linkerd2/issues/1869) with sidecar containers as the sidecar container will not be shut down automatically when the job finishes.
This leaves us with the `haproxy-ingress-internal-kubernetes-ingress-crdjob-xx` pod hanging around in the cluster until it gets manually deleted because the linkerd-proxy container in the pod is not being terminated.
Solution:
- Allow annotations to be set on the job spec (we can then set linkerd.io/inject: disabled for the job only, as for the …

Add possibility to set crdjob annotations

---

kubernetes-ingress/README.md
kubernetes-ingress/ci/deployment-podmonitor-values.yaml
kubernetes-ingress/templates/_helpers.tpl
kubernetes-ingress/templates/controller-podmonitor.yaml
kubernetes-ingress/values.yaml

MINOR: Support PodMonitor as alternative to ServiceMonitor

---

kubernetes-ingress/templates/controller-crdjob.yaml
kubernetes-ingress/templates/controller-daemonset.yaml
kubernetes-ingress/templates/controller-proxy-deployment.yaml

Fix a bug introduced in #276 where controller.podAnnotations was not templatable in every place it was used. This is now fixed.

BUG:  kubernetes-ingress: Fix controller.podAnnotations not being templatable in every location

---

kubernetes-ingress/ci/daemonset-customconfig-templated-values.yaml
kubernetes-ingress/ci/deployment-customconfig-templated-values.yaml
kubernetes-ingress/templates/controller-configmap.yaml

MAJOR: kubernetes-ingress: Make controller.config templatable

---

haproxy/templates/deployment.yaml
haproxy/values.yaml

This feature adds the ability for users to configure annotations on the deployment configuration. This is useful for certain integrations such as Reloader that watches for changes to associated resources.
Example usage:
```yaml
deploymentAnnotations:
reloader.stakater.com/auto: "true"
```

feat(haproxy): Add deployment annotations as a configurable property.

---

haproxy/README.md
haproxy/templates/daemonset.yaml
haproxy/templates/deployment.yaml

feat(haproxy): Conditionalize config volumeMount subpath

---

kubernetes-ingress/templates/controller-daemonset.yaml

This PR improves the port configuration options for the HAProxy chart, allowing for more granular control over containerPorts and hostPorts.
We should be able, when using hostPort, to define part of ports to be containerPorts without making it **always** hostPort as well (as it is currently).
(I.e - we want to bind 80 and 443 from host, and have stats page accessible through service)
Thanks to this change, only ports that are explicitly defined as hostPorts will be bind and accessible publicly.
* In my case, the thing is about stat on port 1024. I want it only accessible from inside the cluster.
Also, stat is set as hostPort by default in [values.yaml ](https://github.com/haproxytech/helm-charts/blob/e3b0b23581fb9abda695c19376f3e22ce65007dd/kubernetes-ingress/values.yaml#L499), but after …

kubernetes-ingress: bind only defined ports as HostPort

---

kubernetes-ingress/templates/_helpers.tpl
kubernetes-ingress/templates/clusterrole.yaml
kubernetes-ingress/templates/clusterrolebinding.yaml
kubernetes-ingress/templates/controller-configmap.yaml
kubernetes-ingress/templates/controller-crdjob.yaml
kubernetes-ingress/templates/controller-daemonset.yaml
kubernetes-ingress/templates/controller-defaultcertsecret.yaml
kubernetes-ingress/templates/controller-deployment.yaml
kubernetes-ingress/templates/controller-hpa.yaml
kubernetes-ingress/templates/controller-ingressclass.yaml
kubernetes-ingress/templates/controller-keda.yaml
kubernetes-ingress/templates/controller-poddisruptionbudget.yaml
kubernetes-ingress/templates/controller-podmonitor.yaml
kubernetes-ingress/templates/controller-podsecuritypolicy.yaml
kubernetes-ingress/templates/controller-proxy-deployment.yaml
kubernetes-ingress/templates/controller-proxy-service.yaml
kubernetes-ingress/templates/controller-pullsecret.yaml
kubernetes-ingress/templates/controller-role.yaml
kubernetes-ingress/templates/controller-rolebinding.yaml
kubernetes-ingress/templates/controller-service-metrics.yaml
kubernetes-ingress/templates/controller-service.yaml
kubernetes-ingress/templates/controller-serviceaccount.yaml
kubernetes-ingress/templates/controller-servicemonitor.yaml
kubernetes-ingress/templates/namespace.yaml

This refactor replaces duplicated label definitions with reusable templates, improving maintainability and reducing redundancy in the Helm chart.

MINOR: Use templates for labels to remove duplication

---

kubernetes-ingress/templates/controller-service.yaml
kubernetes-ingress/values.yaml

This port was confusing as accessing the ingress controller metrics is done on the /metrics but on port http

MINOR: kubernetes-ingress remove port name prometheus from service

---

kubernetes-ingress/templates/controller-daemonset.yaml
kubernetes-ingress/templates/controller-deployment.yaml
kubernetes-ingress/templates/controller-proxy-deployment.yaml
kubernetes-ingress/templates/controller-service.yaml
kubernetes-ingress/values.yaml

Re-adding the kubernetes-ingress service port that was named prometheus but rename it as admin as it exposes KIC metrics and pprof.
To sum up:
Exposed on kubernetes-ingress service port named 'admin':
- KIC Prometheus metrics under: /metrics
- Pprof under: /debug/pprof Exposed on kubernetes-ingress service port named 'stat':
- HAProxy Prometheus metrics under: /metrics

MINOR: kubernetes-ingress add service port named admin

---

kubernetes-ingress/Chart.yaml

This automatic PR updates the appVersion for Ingress controller in Chart.yaml to 3.1.10.

Ingress Controller: update appVersion to 3.1.10

---

kubernetes-ingress/Chart.yaml

This automatic PR updates the appVersion for Ingress controller in Chart.yaml to 3.1.11.

Ingress Controller: update appVersion to 3.1.11

---

haproxy/templates/daemonset.yaml
haproxy/templates/deployment.yaml
haproxy/templates/service.yaml
haproxy/values.yaml

This pull request introduces enhanced flexibility for configuring ports and metadata in the HAProxy Helm chart's Kubernetes manifests. The main improvements are the addition of "raw" configuration options for container and service ports, and the ability to specify custom deployment labels. These changes allow users to define ports and labels with greater detail and control, supporting advanced scenarios.
**Port configuration enhancements:**
* Added support for `rawContainerPorts` in `values.yaml`, allowing users to specify container ports in full Kubernetes format (including custom protocols and names). This is now rendered in both `daemonset.yaml` and `deployment.yaml` templates. [[1]](diffhunk://#diff-dbc40bde5663305c8fdb5dd4eb23c673678ed5317da173913d6fe4ac4b75bf07R180-R191) …

feat: add support for deployment labels, raw container and service additional ports

---

haproxy/templates/keda.yaml
haproxy/values.yaml
kubernetes-ingress/templates/controller-keda.yaml
kubernetes-ingress/values.yaml

This pull request is adding support for configuring a fallback for the KEDA ScaledObject based upon the [documentation](https://keda.sh/docs/2.17/reference/scaledobject-spec/#fallback).

MINOR: add fallback configuration for KEDA
