haproxytech/helm-charts

kubernetes-ingress/Chart.yaml
kubernetes-ingress/templates/controller-daemonset.yaml
kubernetes-ingress/templates/controller-deployment.yaml
kubernetes-ingress/values.yaml

Signed-off-by: Joseph (Jy) Yaworski <yaworski_joseph@bah.com>

Add configuration for pod probes

---

kubernetes-ingress/Chart.yaml
kubernetes-ingress/templates/controller-daemonset.yaml
kubernetes-ingress/templates/controller-deployment.yaml
kubernetes-ingress/values.yaml

Adding initContainers for Controller component

---

kubernetes-ingress/templates/_helpers.tpl
kubernetes-ingress/templates/controller-configmap.yaml
kubernetes-ingress/templates/controller-daemonset.yaml
kubernetes-ingress/templates/controller-deployment.yaml
kubernetes-ingress/values.yaml

Controller logs and traffic logs can both be configured via the
"logging" field.

Add logging options

---

kubernetes-ingress/templates/controller-deployment.yaml
kubernetes-ingress/values.yaml

Support changing the deployment strategy.

Support deployment strategy definition

---

kubernetes-ingress/templates/clusterrole.yaml

RBAC is too permissive for Secrets, and some Resources are unused

---

kubernetes-ingress/templates/controller-daemonset.yaml
kubernetes-ingress/templates/controller-deployment.yaml
kubernetes-ingress/values.yaml

Signed-off-by: Paul Taylor <paul.taylor@equifax.com>

Support for extraContainers and extraVolumes, see #35

---

kubernetes-ingress/templates/controller-daemonset.yaml
kubernetes-ingress/templates/controller-deployment.yaml
kubernetes-ingress/values.yaml

Signed-off-by: Paul Taylor <paul.taylor@equifax.com>

Support for controller lifecycle hooks, see #40

---

kubernetes-ingress/templates/controller-daemonset.yaml
kubernetes-ingress/templates/controller-deployment.yaml
kubernetes-ingress/values.yaml

Signed-off-by: Paul Taylor <paul.taylor@equifax.com>

Support for extra labels on deployments and replicasets, see #42

---

.github/workflows/check.yml

Adding check-commit action to github acions workflow will ensure that all commits in the repo are formatted according to: https://github.com/haproxy/haproxy/blob/master/CONTRIBUTING#L632

BUILD/MINOR: github-ci: add check-commit

---

haproxy/templates/daemonset.yaml
haproxy/templates/deployment.yaml
haproxy/values.yaml

Please evaluate and merge my PR.
Thanks
Denis
Signed-off-by: Denis Maggiorotto <denis.maggiorotto@sunnyvale.it>

daemonset.yaml and deployment.yaml template files have been modified to allow configuring metadata.annotations using values (fix issue #93)

---

haproxy/templates/daemonset.yaml
haproxy/templates/deployment.yaml
haproxy/values.yaml

Signed-off-by: Ronan Lanore <ronan.lanore@gmail.com>

Add liveness probe to regular haproxy daemonset

---

haproxy/templates/daemonset.yaml
haproxy/templates/deployment.yaml

Creating PR for https://github.com/haproxytech/helm-charts/issues/120

use subpath for mounting haproxy.cfg file only

---

kubernetes-ingress/templates/controller-servicemonitor.yaml

Signed-off-by: Jérémy Bertozzi <jeremy.bertozzi@gmail.com>

BUG: haproxy-ingress: add namespace to controller servicemonitor

---

haproxy/templates/daemonset.yaml
haproxy/templates/deployment.yaml
kubernetes-ingress/templates/controller-daemonset.yaml
kubernetes-ingress/templates/controller-deployment.yaml

Hi, team.
I fixed a configuration error that occurred in [this PR](https://github.com/haproxytech/helm-charts/pull/128).

fix(all): misconfiguration for several probes.

---

haproxy/ci/daemonset-ingress-values.yaml
haproxy/ci/deployment-ingress-values.yaml
haproxy/templates/ingress.yaml
haproxy/values.yaml

Hi, team.
I added a template for ingress to HAProxy chart.

feat(haproxy): add ingress template for haproxy.

---

haproxy/templates/daemonset.yaml
haproxy/templates/deployment.yaml
haproxy/values.yaml

- Separated: main config file and include config
- Added configure mount path: includes files and maps

Separated main config file and include config

---

kubernetes-ingress/templates/controller-hpa.yaml
kubernetes-ingress/templates/default-backend-hpa.yaml
kubernetes-ingress/values.yaml

Signed-off-by: j_menan <julien.menan@bedrockstreaming.com>
allow to add annotation on the `HPA`

feat(hpa): authorize annotations

---

haproxy/README.md
haproxy/templates/daemonset.yaml
haproxy/templates/deployment.yaml
haproxy/values.yaml

Closes #95 and #136
Signed-off-by: David Phillips <david@yeah.nah.nz>

FEATURE/MINOR: haproxy: add extraEnvs to helm values (#95, #136)

---

kubernetes-ingress/templates/clusterrole.yaml

Added get permission for endpointslices

Add missing permission to clusterrole

---

haproxy/templates/daemonset.yaml
haproxy/templates/deployment.yaml
haproxy/values.yaml

Fixes issue #152 
Signed-off-by: Sebastian Greco <38133294+pupseba@users.noreply.github.com>

minReadySeconds is configurable

---

haproxy/Chart.yaml
haproxy/templates/daemonset.yaml
haproxy/templates/deployment.yaml

fixes #166
rendering now looks like this:
```
containers:
- name: haproxy
securityContext:
runAsGroup: 1000
runAsUser: 1000
```

fix(security-context): Fix rendering of securityContext in haproxy chart

---

haproxy/Chart.yaml
haproxy/templates/hpa.yaml

chore(haproxy): update HPA API version.

---

haproxy/Chart.yaml
haproxy/templates/hpa.yaml

Sorry, https://github.com/haproxytech/helm-charts/pull/172 has wrong spec, i fixed it.

fix(haproxy): HPA spec.

---

haproxy/templates/daemonset.yaml
haproxy/templates/deployment.yaml
haproxy/values.yaml

- Adds the ability to use envFrom in the deployment and deamonset

(haproxy) -  Adds envFrom to Deployment and Deamonset

---

haproxy/templates/daemonset.yaml
haproxy/templates/deployment.yaml

Fixes haproxytech/helm-charts#258

Remove pod annotations from deployment

---

kubernetes-ingress/ci/deployment-podmonitor-values.yaml

Follow up PR for #271 fixing a test values.

MINOR: Use correct values for PodMonitor test

---

kubernetes-ingress/Chart.yaml

This automatic PR updates the appVersion for Ingress controller in Chart.yaml to 3.1.9.

Ingress Controller: update appVersion to 3.1.9
